name: build binaries

on:
  push:
    tags:
      - "cv*"

jobs:
  build_matrix:
    strategy:
      matrix:
        env: [linux, windows, macos_M1, macos_Intel]
        include:
          - env: linux
            os: ubuntu-latest
            bin: twitchTransFN
            archive: tar.gz
          - env: windows
            os: windows-latest
            bin: twitchTransFN.exe
            archive: zip
          - env: macos_M1
            os: macos-latest
            bin: twitchTransFN.command
            archive: tar.gz
            arch: _arm64
          - env: macos_Intel
            os: macos-latest
            bin: twitchTransFN.command
            archive: tar.gz
            arch: _x86_64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip and install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install Linux dependencies for Nuitka
        if: matrix.env == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf
          python -m pip install nuitka

      - name: Install macOS dependencies for Nuitka and build icon.icns
        if: startsWith(matrix.env, 'macos')
        run: |
          brew install zstd imagemagick
          python -m pip install nuitka
          mkdir icon.iconset
          sips -z 16 16     icon.png --out icon.iconset/icon_16x16.png
          sips -z 32 32     icon.png --out icon.iconset/icon_16x16@2x.png
          sips -z 32 32     icon.png --out icon.iconset/icon_32x32.png
          sips -z 64 64     icon.png --out icon.iconset/icon_32x32@2x.png
          sips -z 128 128   icon.png --out icon.iconset/icon_128x128.png
          sips -z 256 256   icon.png --out icon.iconset/icon_128x128@2x.png
          sips -z 256 256   icon.png --out icon.iconset/icon_256x256.png
          sips -z 512 512   icon.png --out icon.iconset/icon_256x256@2x.png
          sips -z 512 512   icon.png --out icon.iconset/icon_512x512.png
          cp icon.png icon.iconset/icon_512x512@2x.png
          iconutil -c icns icon.iconset -o icon.icns

      - name: Install Nuitka for Windows
        if: matrix.env == 'windows'
        run: python -m pip install nuitka

      - name: Install Python requirements
        run: python -m pip install -r requirements.txt

      - name: Download cacert.pem
        run: curl -o cacert.pem https://curl.se/ca/cacert.pem

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep "version =" twitchTransFN.py | awk -F "'" '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with Nuitka
        run: |
          mkdir -p dist
          COMMON_ARGS="--standalone --onefile --follow-imports --output-dir=dist --output-filename=${{ matrix.bin }}"
          if [ "${{ matrix.env }}" == "windows" ]; then
            nuitka $COMMON_ARGS --windows-icon-from-ico=icon.ico twitchTransFN.py
          elif [ "${{ matrix.env }}" == "linux" ]; then
            nuitka $COMMON_ARGS --linux-icon=icon.ico twitchTransFN.py
          elif [ "${{ matrix.env }}" == "macos_M1" ] || [ "${{ matrix.env }}" == "macos_Intel" ]; then
            nuitka $COMMON_ARGS --macos-app-icon=icon.icns --macos-create-app-bundle twitchTransFN.py
          fi

      - name: Sign the binary with GPG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --batch --yes --passphrase "$GPG_PASSPHRASE" -ab dist/${{ matrix.bin }}

      - name: Archive Binary (zip)
        if: matrix.archive == 'zip'
        run: powershell Compress-Archive -Path dist/* -DestinationPath twitchTransFN_${{ steps.get_version.outputs.version }}_${{ matrix.env }}.zip

      - name: Archive Binary (tar.gz)
        if: matrix.archive == 'tar.gz'
        run: |
          ARCHIVE_NAME="twitchTransFN_${{ steps.get_version.outputs.version }}_${{ matrix.env }}"
          mv dist "$ARCHIVE_NAME"
          tar -czvf "$ARCHIVE_NAME.tar.gz" "$ARCHIVE_NAME"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            twitchTransFN_${{ steps.get_version.outputs.version }}_${{ matrix.env }}.${{ matrix.archive }}
            dist/${{ matrix.bin }}.asc

      - name: Clean up
        run: rm -rf dist *.tar.gz *.zip *.asc || true
